"""Regenerate src/cleaner/text/tables.py from the Unicode Character Database.

Run: uv run python tools/gen_tables.py

Vendoring the ranges keeps the runtime dependency-free and pins behaviour to a
known UCD version, rather than varying with whatever unicodedata2 is installed.
"""
from __future__ import annotations

import pathlib
import re
import urllib.request

BASE = "https://www.unicode.org/Public/UCD/latest/ucd"
SCRIPTS_URL = f"{BASE}/Scripts.txt"
EMOJI_URL = f"{BASE}/emoji/emoji-data.txt"

# Scripts where ZWJ/ZWNJ carry meaning: they select joining forms in cursive
# scripts and form conjuncts/half-forms in Indic ones. Stripping them here
# corrupts words.
JOINING_SCRIPTS = {
    "Arabic", "Syriac", "Thaana", "Nko", "Mandaic", "Adlam",
    "Devanagari", "Bengali", "Gurmukhi", "Gujarati", "Oriya", "Tamil",
    "Telugu", "Kannada", "Malayalam", "Sinhala", "Myanmar", "Khmer",
    "Tibetan", "Mongolian", "Javanese", "Balinese", "Chakma", "Tirhuta",
}

RANGE_RE = re.compile(
    r"^([0-9A-F]{4,6})(?:\.\.([0-9A-F]{4,6}))?\s*;\s*([^#]+?)\s*(?:#|$)", re.M
)


def fetch(url: str) -> str:
    with urllib.request.urlopen(url) as response:
        return response.read().decode("utf-8")


def parse(text: str, wanted) -> list[tuple[int, int]]:
    ranges = []
    for match in RANGE_RE.finditer(text):
        lo, hi, prop = match.group(1), match.group(2), match.group(3).strip()
        if not wanted(prop):
            continue
        start = int(lo, 16)
        ranges.append((start, int(hi, 16) if hi else start))
    return merge(ranges)


def merge(ranges: list[tuple[int, int]]) -> list[tuple[int, int]]:
    ranges.sort()
    out: list[tuple[int, int]] = []
    for lo, hi in ranges:
        if out and lo <= out[-1][1] + 1:
            out[-1] = (out[-1][0], max(out[-1][1], hi))
        else:
            out.append((lo, hi))
    return out


def version_of(text: str) -> str:
    match = re.search(r"# Scripts-([\d.]+)\.txt|# emoji-data-([\d.]+)\.txt", text)
    return (match.group(1) or match.group(2)) if match else "unknown"


def fmt(name: str, ranges: list[tuple[int, int]]) -> str:
    lines = [f"{name}: tuple[tuple[int, int], ...] = ("]
    for lo, hi in ranges:
        lines.append(f"    (0x{lo:04X}, 0x{hi:04X}),")
    lines.append(")")
    return "\n".join(lines)


def main() -> None:
    scripts_txt = fetch(SCRIPTS_URL)
    emoji_txt = fetch(EMOJI_URL)
    joining = parse(scripts_txt, lambda p: p in JOINING_SCRIPTS)
    picto = parse(emoji_txt, lambda p: p == "Extended_Pictographic")

    out = pathlib.Path("src/cleaner/text/tables.py")
    out.write_text(f'''"""Generated by tools/gen_tables.py -- do not edit by hand.

Unicode Scripts {version_of(scripts_txt)} / emoji-data {version_of(emoji_txt)}.
"""

# Scripts in which ZWJ (U+200D) and ZWNJ (U+200C) are meaningful rather than
# noise: {", ".join(sorted(JOINING_SCRIPTS))}.
{fmt("JOINING_SCRIPT_RANGES", joining)}

# Extended_Pictographic: the base characters of emoji ZWJ sequences.
{fmt("EXTENDED_PICTOGRAPHIC_RANGES", picto)}
''')
    print(f"wrote {out}: {len(joining)} joining ranges, {len(picto)} pictographic ranges")


if __name__ == "__main__":
    main()
